
#!/usr/bin/env python3
import base64
import json
import os
import sys
import tempfile
from http.server import BaseHTTPRequestHandler, HTTPServer
import cgi
import io
import traceback

# Import Pretty GPX modules
# Note: In a real implementation, these would be actual imports
# from prettygpx import generate_poster, extract_metadata

class PrettyGPXHandler(BaseHTTPRequestHandler):
    def _set_headers(self, content_type="application/json"):
        self.send_response(200)
        self.send_header("Content-type", content_type)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()
        
    def do_OPTIONS(self):
        self._set_headers()
        self.wfile.write(json.dumps({}).encode())
        
    def do_POST(self):
        try:
            content_length = int(self.headers["Content-Length"])
            post_data = self.rfile.read(content_length)
            data = json.loads(post_data.decode("utf-8"))
            
            # Extract GPX content and options
            gpx_base64 = data.get("gpx_content", "")
            options = data.get("options", {})
            
            # Decode the GPX file
            gpx_content = base64.b64decode(gpx_base64)
            
            # Create a temporary file to store the GPX data
            with tempfile.NamedTemporaryFile(suffix=".gpx", delete=False) as temp_gpx:
                temp_gpx.write(gpx_content)
                temp_gpx_path = temp_gpx.name
                
            # Process the GPX file (mock implementation)
            # In a real implementation, we would call Pretty GPX functions here
            # image_path, pdf_path = generate_poster(temp_gpx_path, options)
            # metadata = extract_metadata(temp_gpx_path)
            
            # Mock implementation
            metadata = {
                "title": "Sample GPX Track",
                "distance": 15.2,
                "elevation": 350,
                "duration": "1h 30m",
                "date": "2025-05-21",
            }
            
            # Generate mock image and PDF (in a real implementation, these would be generated by Pretty GPX)
            image_data = "Mock image data that would be generated by Pretty GPX"
            pdf_data = "Mock PDF data that would be generated by Pretty GPX"
            
            # In a real implementation, we would return the actual image and PDF data
            response = {
                "image_data": base64.b64encode(image_data.encode()).decode(),
                "pdf_data": base64.b64encode(pdf_data.encode()).decode(),
                "metadata": metadata
            }
            
            # Clean up the temporary file
            os.unlink(temp_gpx_path)
            
            # Send the response
            self._set_headers()
            self.wfile.write(json.dumps(response).encode())
        
        except Exception as e:
            self.send_response(500)
            self.send_header("Content-type", "application/json")
            self.end_headers()
            error_response = {
                "error": str(e),
                "traceback": traceback.format_exc()
            }
            self.wfile.write(json.dumps(error_response).encode())

def run_server(port=8080):
    server_address = ("", port)
    httpd = HTTPServer(server_address, PrettyGPXHandler)
    print(f"Starting PrettyGPX server on port {port}")
    httpd.serve_forever()

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8080))
    run_server(port)
