// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojdklhnblzbpoewzttvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qZGtsaG5ibHpicG9ld3p0dHZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MjgwNjUsImV4cCI6MjA2MzQwNDA2NX0.Pbz2cZukkRLzMuHRsaky1LkAp-6F0Y75EYMuiQ2fXQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);